name: WakaTime Readme

on:
  schedule:
    # Updates every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          LANG_COUNT: 7
          SHOW_TIME: true
